# Setup
title:              reviewNote 
tagline:             'Making less mistake and remember'
description:         'Stupid, but growing'
url:                 https://withgod84.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:             Deokkoo Kim
  url:               https://twitter.com/mdo
  email:             withgod84@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
